In [ ]:
import numpy as np

move_x = [2, 1, -1, -2, -2, -1, 1, 2]
move_y = [1, 2, 2, 1, -1, -2, -2, -1]

board = np.zeros((8, 8))

board[3, 2] = 1

In [ ]:
def validate_move(board, row, col):
    if row < 8 and row >= 0 and col < 8 and col >= 0 and board[row, col] == 0:
        return True

In [ ]:
def solve(board, row, col, n, counter):

    for i in range(n):
        if counter >= n**2:
            return True

    new_x = row + move_x[i]
    new_y = col + move_y[i]

    if validate_move(board, new_x, new_y):
        board[new_x, new_y] = counter
        if solve(board, new_x, new_y, n, counter + 1):
            return True
        board[new_x, new_y] = 0

    return False

In [ ]:
import ipdb

row = 3
col = 2
counter = 2

for i in range(8):
        if counter >= 65:
            True
        
new_x = row + move_x[i]
new_y = col + move_y[i]

ipdb.set_trace()

if validate_move(board, new_x, new_y):
        board[new_x, new_y] = counter
        if solve(board, new_x, new_y, 8, counter + 1):
            return True
        board[new_x, new_y] = 0

False

In [ ]:
import numpy as np

move_x = [2, 1, -1, -2, -2, -1, 1, 2]
move_y = [1, 2, 2, 1, -1, -2, -2, -1]

board = np.zeros((8, 8))

board[3, 2] = 1


def validate_move(board, row, col):
    if row < 8 and row >= 0 and col < 8 and col >= 0 and board[row, col] == 0:
        return True


def solve(board, row, col, n, counter):

    for i in range(n):
        if counter >= n**2:
            return True

    new_x = row + move_x[i]
    new_y = col + move_y[i]

    if validate_move(board, new_x, new_y):
        board[new_x, new_y] = counter
        if solve(board, new_x, new_y, n, counter + 1):
            return True
        board[new_x, new_y] = 0

    return False


solve(board, 3, 2, 8, 2)
print(board.sum())
print(board)

In [2]:
sixtyfour = [[38. 57. 30. 55. 14. 49. 28.  7.]
 [31. 54. 39. 50. 29.  8. 13.  0.]
 [58. 37. 56. 25. 48. 15.  6. 27.]
 [53. 32.  1. 40. 51. 26.  9. 12.]
 [36. 59. 52. 47. 24. 11. 16.  5.]
 [45. 62. 33.  2. 41. 18. 21. 10.]
 [60. 35. 46. 43. 20. 23.  4. 17.]
 [63. 44. 61. 34.  3. 42. 19. 22.]]

SyntaxError: invalid syntax (<ipython-input-2-ea68f059c779>, line 1)

In [ ]:
sixtyfive = [[38. 53. 30. 57. 14. 63. 28.  7.]
 [31. 58. 39. 62. 29.  8. 13. 64.]
 [52. 37. 54. 25. 56. 15.  6. 27.]
 [59. 32.  1. 40. 61. 26.  9. 12.]
 [36. 51. 60. 55. 24. 11. 16.  5.]
 [45. 48. 33.  2. 41. 18. 21. 10.]
 [50. 35. 46. 43. 20. 23.  4. 17.]
 [47. 44. 49. 34.  3. 42. 19. 22.]]