In [135]:
import numpy as np


def validate(board, n):
    for row in range(0,n):
        if sum(board[row,])>1:
            return False
        
    for col in range(0,n):
        if sum(board[:,col])>1:
            return False
        
    diags = [board[::-1,:].diagonal(i) for i in range(-n+2, n-1)]
    diags.extend(board.diagonal(i) for i in range(n-2, -n+1, -1))
    
    for x in diags:
        if sum(x) > 1:
            return False
    return True        

def solve(board, col, n):
    
    if validate(board,n):
        if board.sum()==n:
            return True
        
    for row in range(0,n):
        board[row,col] = 1
        if validate(board,n):
            if solve(board, col+1, n):
                return True
            board[row,col] = 0
        else:
           board[row,col] = 0
    return False
board = np.zeros((8,8))
if solve(board, 0, 8):
    print(board)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]]


In [137]:
board

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.]])

In [48]:
grid = [
    [7,8,4,  1,5,9,  3,2,6],
    [5,3,9,  6,7,2,  8,4,1],
    [6,1,2,  4,3,8,  7,5,9],

    [9,2,8,  7,1,5,  4,6,3],
    [3,5,7,  8,4,6,  1,9,2],
    [4,6,1,  9,2,3,  5,8,7],

    [8,7,6,  3,9,4,  2,1,5],
    [2,4,3,  5,6,1,  9,7,8],
    [1,9,5,  2,8,7,  6,3,4]
]

In [ ]:
grid2 = np.array(grid)

In [ ]:
a_rev = a[::-1,:]

for i in range(-4,1,4):
    print(a_rev.diagonal(i))

diags =  np.array([[board[::-1,:]].diagonal(i) for i in range(-8, 1 ,8)]    )

a = np.arange(16).reshape(4,4)
a

np.diagonal(board)

diags.extend(board.diagonal(i) for i in range(n-1, -n, -1))

In [139]:
x,y = 8,8
a = np.arange(x*y).reshape(x,y)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [99]:
a[::-1]

array([[56, 57, 58, 59, 60, 61, 62, 63],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [ 0,  1,  2,  3,  4,  5,  6,  7]])

In [100]:
a.shape

(8, 8)

In [101]:
a.shape[0],a.shape[1]

(8, 8)

In [72]:
for i in range(-a.shape[0]+1, a.shape[1]):
    print(a[::-1,:].diagonal(i))

[0]
[4 1]
[8 5 2]
[12  9  6  3]
[13 10  7]
[14 11]
[15]


In [81]:
for i in range(-2,3):
    diagonals_list.append(a[::-1,:].diagonal(i))

In [91]:
for i in range(2,-3,-1):
    print(a.diagonal(i))

[2 7]
[ 1  6 11]
[ 0  5 10 15]
[ 4  9 14]
[ 8 13]


In [ ]:
for i in range(-a.shape[0]+1, a.shape[1]):
    print(a[::-1,:].diagonal(i))

In [ ]:
diags = [a[::-1,:].diagonal(i) for i in range(-4, 1 ,4)]

In [80]:
diagonals_list=[]

In [83]:
diagonals_list

[array([4, 1]),
 array([8, 5, 2]),
 array([12,  9,  6,  3]),
 array([13, 10,  7]),
 array([14, 11]),
 array([2, 7]),
 array([ 1,  6, 11]),
 array([ 0,  5, 10, 15]),
 array([ 4,  9, 14]),
 array([ 8, 13])]

In [85]:
print([n.tolist() for n in diagonals_list])

[[4, 1], [8, 5, 2], [12, 9, 6, 3], [13, 10, 7], [14, 11], [2, 7], [1, 6, 11], [0, 5, 10, 15], [4, 9, 14], [8, 13]]


In [106]:
diags = [a[::-1,:].diagonal(i) for i in range(-6, 7)]

diags.extend(a.diagonal(i) for i in range(6, -7, -1))

In [109]:
diags

[array([8, 1]),
 array([16,  9,  2]),
 array([24, 17, 10,  3]),
 array([32, 25, 18, 11,  4]),
 array([40, 33, 26, 19, 12,  5]),
 array([48, 41, 34, 27, 20, 13,  6]),
 array([56, 49, 42, 35, 28, 21, 14,  7]),
 array([57, 50, 43, 36, 29, 22, 15]),
 array([58, 51, 44, 37, 30, 23]),
 array([59, 52, 45, 38, 31]),
 array([60, 53, 46, 39]),
 array([61, 54, 47]),
 array([62, 55]),
 array([ 6, 15]),
 array([ 5, 14, 23]),
 array([ 4, 13, 22, 31]),
 array([ 3, 12, 21, 30, 39]),
 array([ 2, 11, 20, 29, 38, 47]),
 array([ 1, 10, 19, 28, 37, 46, 55]),
 array([ 0,  9, 18, 27, 36, 45, 54, 63]),
 array([ 8, 17, 26, 35, 44, 53, 62]),
 array([16, 25, 34, 43, 52, 61]),
 array([24, 33, 42, 51, 60]),
 array([32, 41, 50, 59]),
 array([40, 49, 58]),
 array([48, 57])]

In [164]:
[n.tolist() for n in a][0]

[0, 1, 2, 3, 4, 5, 6, 7]

In [156]:
# a[0,:] == a[0,] == a[0]
a[0] == a[0,]

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [146]:
for row in range(0,8):
    print(a[row,])

[0 1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14 15]
[16 17 18 19 20 21 22 23]
[24 25 26 27 28 29 30 31]
[32 33 34 35 36 37 38 39]
[40 41 42 43 44 45 46 47]
[48 49 50 51 52 53 54 55]
[56 57 58 59 60 61 62 63]


In [166]:
board[3, 2] = 64
board

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0., 64.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.]])